2022-10-28 00:19:29.336 -05:00 [ERR] Connection id "0HMLOKF48ESPL", Request id "0HMLOKF48ESPL:00000013": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Sucedió un inconveniente al procesar su solicitud, por favor vuelva a intentar en unos minutos
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.RegisterComandoProxy.Registrar(Register reqgister) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\RegisterComandoProxy.cs:line 20
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.RegisterController.Registrar(Register request) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\RegisterController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
2022-10-28 00:20:18.703 -05:00 [ERR] Connection id "0HMLOKF48ESPL", Request id "0HMLOKF48ESPL:00000014": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Sucedió un inconveniente al procesar su solicitud, por favor vuelva a intentar en unos minutos
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.RegisterComandoProxy.Registrar(Register reqgister) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\RegisterComandoProxy.cs:line 20
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.RegisterController.Registrar(Register request) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\RegisterController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
2022-10-28 00:22:12.293 -05:00 [ERR] Connection id "0HMLOKF48ESPL", Request id "0HMLOKF48ESPL:00000015": An unhandled exception was thrown by the application.
System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Release.Helper.Proxy.ProxyHttpClient.InvokeWebApi[T](HttpMethod verb, String url, String jsonData, String defaultMediaType, String authorizationToken, String authorizationMethod, Int32 timeout)
   at Release.Helper.Proxy.BaseProxy.InvokeWebApi[T](HttpMethod verb, String urlAction, String parameters, Int32 timeout)
   at Prod.GESTORPLUS.Presentacion.Configuracion.Proxys.RegisterComandoProxy.Registrar(Register reqgister) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.Configuracion\Proxys\RegisterComandoProxy.cs:line 20
   at Prod.GESTORPLUS.Presentacion.MVC.Controllers.RegisterController.Registrar(Register request) in C:\gestorplus\Prod.GESTORPLUS.Presentacion.MVC\Controllers\RegisterController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

